### ISSUE TITLE
Bump `pear/pear_exception` version to 1.0.1

### ISSUE THREAD

**Issue by MikeyMJCO** [pear/Log#14]
Can we bump the `pear/pear_exception` version to the current release/stable of 1.0.1. 

I've tested this locally and can't find any obvious compatibility issues that this would introduce.

**Comment by ashnazg** [comment]
Is there a concrete reason to prevent 1.0.0 from continuing to be usable?

**Comment by ashnazg** [comment]
Never mind... it looks like that patch change in pear_exception helped fix a composer behavior issue, so now I better understand.
